[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$CraftSimRoot,

  [string]$OutputPath
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$dataRoot = Join-Path $CraftSimRoot "Data\SpecializationData"
if (-not (Test-Path -LiteralPath $dataRoot -PathType Container)) {
  throw "CraftSim specialization data was not found: $dataRoot"
}

if (-not $OutputPath) {
  $OutputPath = Join-Path $projectRoot "Data\RecipeSpecializations.lua"
} elseif (-not [System.IO.Path]::IsPathRooted($OutputPath)) {
  $OutputPath = Join-Path $projectRoot $OutputPath
}
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)

function Get-SectionEntries {
  param(
    [string[]]$Lines,
    [string]$SectionName
  )

  $insideSection = $false
  $entryID = $null
  $entryLines = [System.Collections.Generic.List[string]]::new()
  $entries = [ordered]@{}

  foreach ($line in $Lines) {
    if (-not $insideSection) {
      if ($line -match "^\t${SectionName} = \{$") {
        $insideSection = $true
      }
      continue
    }

    if ($null -eq $entryID) {
      if ($line -match '^\t\t\[(\d+)\] = \{$') {
        $entryID = [int64]$Matches[1]
        $entryLines.Clear()
      } elseif ($line -eq "`t},") {
        break
      }
      continue
    }

    if ($line -eq "`t`t},") {
      $entries[$entryID] = @($entryLines)
      $entryID = $null
      continue
    }

    $entryLines.Add($line)
  }

  return $entries
}

$recipes = @{}
$nodes = @{}
$sourceFiles = Get-ChildItem -LiteralPath $dataRoot -Recurse -Filter "*.lua" |
  Where-Object { $_.Name -ne "SpecializationData.lua" } |
  Sort-Object FullName

foreach ($sourceFile in $sourceFiles) {
  $lines = Get-Content -LiteralPath $sourceFile.FullName
  $recipeEntries = Get-SectionEntries -Lines $lines -SectionName "recipeMapping"
  $nodeEntries = Get-SectionEntries -Lines $lines -SectionName "nodeData"
  $parsedNodes = @{}

  foreach ($pair in $nodeEntries.GetEnumerator()) {
    $nodeID = $null
    $maxRank = $null
    $skill = 0

    foreach ($line in $pair.Value) {
      if ($line -match '^\t\t\tnodeID = (\d+),$') {
        $nodeID = [int64]$Matches[1]
      } elseif ($line -match '^\t\t\tmaxRank = (\d+),$') {
        $maxRank = [int]$Matches[1]
      } elseif ($line -match '^\t\t\t\tskill = ([\d.]+),$') {
        $skill = [double]::Parse($Matches[1], [Globalization.CultureInfo]::InvariantCulture)
      }
    }

    if ($null -ne $nodeID -and $null -ne $maxRank) {
      $parsedNodes[[int64]$pair.Key] = [pscustomobject]@{
        Key = [int64]$pair.Key
        NodeID = $nodeID
        MaxRank = $maxRank
        Skill = $skill
      }

      if ([int64]$pair.Key -eq $nodeID) {
        if (-not $nodes.ContainsKey($nodeID)) {
          $nodes[$nodeID] = [ordered]@{
            MaxRank = $maxRank
            SkillPerRank = $skill
            Perks = @{}
          }
        }
      }
    }
  }

  foreach ($parsedNode in $parsedNodes.Values) {
    if ($parsedNode.Key -ne $parsedNode.NodeID -and $parsedNode.Skill -gt 0) {
      if (-not $nodes.ContainsKey($parsedNode.NodeID)) {
        $nodes[$parsedNode.NodeID] = [ordered]@{
          MaxRank = 0
          SkillPerRank = 0
          Perks = @{}
        }
      }
      $nodes[$parsedNode.NodeID].Perks[$parsedNode.Key] = $parsedNode.Skill
    }
  }

  foreach ($pair in $recipeEntries.GetEnumerator()) {
    $relatedNodeIDs = [System.Collections.Generic.HashSet[int64]]::new()
    foreach ($line in $pair.Value) {
      if ($line -match '^\t\t\t(\d+),$') {
        $mappedID = [int64]$Matches[1]
        $parsedNode = $parsedNodes[$mappedID]
        if ($parsedNode -and $parsedNode.Skill -gt 0) {
          [void]$relatedNodeIDs.Add($parsedNode.NodeID)
        }
      }
    }

    if ($relatedNodeIDs.Count -gt 0) {
      $recipeID = [int64]$pair.Key
      if (-not $recipes.ContainsKey($recipeID)) {
        $recipes[$recipeID] = [System.Collections.Generic.HashSet[int64]]::new()
      }
      foreach ($nodeID in $relatedNodeIDs) {
        [void]$recipes[$recipeID].Add($nodeID)
      }
    }
  }
}

$usedNodeIDs = [System.Collections.Generic.HashSet[int64]]::new()
foreach ($recipeNodeIDs in $recipes.Values) {
  foreach ($nodeID in $recipeNodeIDs) {
    [void]$usedNodeIDs.Add($nodeID)
  }
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('local _, addon = ...')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('-- Generated by scripts/Generate-SpecializationData.ps1. Do not edit by hand.')
[void]$builder.AppendLine('addon.SpecializationData = {')
[void]$builder.AppendLine('    recipes = {')
foreach ($recipeID in ($recipes.Keys | Sort-Object)) {
  $nodeList = ($recipes[$recipeID] | Sort-Object) -join ", "
  [void]$builder.AppendLine("        [$recipeID] = {$nodeList},")
}
[void]$builder.AppendLine('    },')
[void]$builder.AppendLine('    nodes = {')
foreach ($nodeID in ($usedNodeIDs | Sort-Object)) {
  $node = $nodes[$nodeID]
  $skillPerRank = $node.SkillPerRank.ToString([Globalization.CultureInfo]::InvariantCulture)
  $perks = @()
  foreach ($perkID in ($node.Perks.Keys | Sort-Object)) {
    $skill = $node.Perks[$perkID].ToString([Globalization.CultureInfo]::InvariantCulture)
    $perks += "{$perkID, $skill}"
  }
  [void]$builder.Append("        [$nodeID] = {$($node.MaxRank), $skillPerRank")
  if ($perks.Count -gt 0) {
    [void]$builder.Append(", {" + ($perks -join ", ") + "}")
  }
  [void]$builder.AppendLine('},')
}
[void]$builder.AppendLine('    },')
[void]$builder.AppendLine('}')

$outputDirectory = [System.IO.Directory]::GetParent($OutputPath).FullName
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
[System.IO.File]::WriteAllText($OutputPath, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $($recipes.Count) recipe mappings and $($usedNodeIDs.Count) skill nodes: $OutputPath"
